input AnswerInput {
    userID: Int!
    questionID: Int!
    type: String!
    content: String!
}

type Answer {
    id: Int
    userID: Int!
    questionID: Int!
    type: String!
    content: String!
}

type Query {
    answers: [Answer]
    answer(id: Int!): Answer
}

type Mutation {
    answerCreate(input: AnswerInput): Answer
    answerUpdate(id: Int!, input: AnswerInput): Answer
}
