input CourseInput {
    userID: Int!
    courseID: Int!
    name: String!	
    description: String!
}

type Course {
    id: Int!
    name: String!
    description: String!
}

type Query {
    courses: [Course]
    course(id: Int!): Course
    courseGetUsers(id: Int!): [User]
    courseGetQuizzes(id: Int!): [Quiz]
}

type Mutation {
    courseCreate(input: CourseInput): Course
}
