input CourseInput {
    id: Int!
    name: String!	
}

type Course {
    id: Int!
    name: String!
}

type Query {
    courses: [Course]
    course(name: String!): Course
}

type Mutation {
    courseCreate(input: CourseInput): Course
}
