input QuestionInput {
    quizID: Int!
    qIndex: Int!
    type: String!
    question: String!
    image: String!
    options: String!
    correctAnswer: String!
    isManual: Boolean!
}

type Question {
    id: Int!
    quizID: Int!
    qIndex: Int!
    type: String!
    question: String!
    image: String!
    options: String!
    correctAnswer: String!
    isManual: Boolean!
}

type Query {
    questions: [Question]
    question(id: Int!): Question
    questionGetUserAnswer(questionID: Int!, userID: Int!): Answer
}

type Mutation {
    questionCreate(input: QuestionInput): Quiz
    questionUpdate(id: Int!, input: QuestionInput): Quiz
}
 
