input QuizInput {
    courseID: Int!
    type: String!
    date: String!
    question: String!
    image: String!
    options: String!
    correctAnswer: String!
    isOpen: Boolean!
    isManual: Boolean!
}

type Quiz {
    id: Int!
    courseID: Int!
    type: String!
    date: String!
    question: String!
    image: String!
    options: String!
    correctAnswer: String!
    isOpen: Boolean!
    isManual: Boolean!
}

type Query {
    quizzes: [Quiz]
    quiz(id: Int!): Quiz
}

type Mutation {
    quizCreate(input: QuizInput): Quiz
    quizUpdate(id: Int!, input: QuizInput): Quiz
}