input QuizInput {
    courseID: Int!
    date: String!
    isOpen: Boolean!
}

type Quiz {
    id: Int!
    courseID: Int!
    date: String!
    isOpen: Boolean!
}

type Query {
    quizzes: [Quiz]
    quiz(id: Int!): Quiz
}

type Mutation {
    quizCreate(input: QuizInput): Quiz
    quizUpdate(id: Int!, input: QuizInput): Quiz
}

type Subscription {
    quizOpened(courseID: Int!): Quiz
}