input SectionInput {
    courseID: Int!
    name: String!
}

type Section {
    id: Int!
    courseID: Int!
    name: String!
}

type Query {
    sections: [Section]
    section(id: Int!): Section
}

type Mutation {
    sectionCreate(input: SectionInput): Section
    sectionUpdate(id: Int!, input: SectionInput): Section
}