input UserInput {
    firstName: String!
    lastName: String!
    email: String!
}

type User {
    id: Int
    firstName: String!
    lastName: String!
    email: String!
    jwt: String!
    courses: [Course]
}

type Query {
    users: [User]
    user(email: String!): User
}

type Mutation {
    login(email: String!, password: String): User
    userCreate(input: UserInput, password: String!): User
    userUpdate(id: Int!, input: UserInput): User
    userAddCourse(id: Int!, c_id: Int!): [Course]
    userGetCourses(id: Int!): [Course]
}