import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../style/styles';

export default StyleSheet.create({
  navigationButton: {
    //flex: 1,
    resizeMode: 'contain',
    paddingTop: 70,
    paddingLeft: 70,
  },
  gradesListView: {
    paddingLeft: 10,
    flex: 2,
  },
  gradeListText: {
    fontFamily: 'Fira Sans',
    fontWeight: '600',
    flex: 1,
    fontSize: 30,
    color: 'black',
    textAlign: 'left',
    paddingLeft: 20
  },
  classHeaderText: {
    //flex: 1,
    fontFamily: 'Fira Sans',
    color: 'black',
    fontWeight: 'bold',
    fontSize: 60,
    textAlign: 'left',
    width: 200,
    paddingLeft: 10,
 },
  classReminderText: {
    fontFamily: 'Fira Sans',
    color: 'grey',
    fontStyle: 'italic',
    fontSize: 18,
    textAlign: 'left',
    width: 300,
    paddingLeft: 20,
  },
  liveQuizReminder: {
    fontFamily: 'Fira Sans',
    color: 'red',
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'center',
    width: 200,
    paddingTop: 200,
    paddingRight: 10,
    //paddingLeft: 20,
  },
  currentGrade: {
    fontFamily: 'Fira Sans',
    color: 'black',
    fontWeight: 'bold',
    fontSize: 30,
    textAlign: 'left',
    width: 600,
    paddingTop: 10,
    paddingLeft: 20,
  },
  gradeTitle: {
    fontFamily: 'Fira Sans',
    color: 'black',
    fontWeight: 'bold',
    fontSize: 40,
    textAlign: 'left',
    width: 600,
    paddingTop: 10,
    paddingLeft: 20,
  }, 
  gradeQuizTitle: {
    fontFamily: 'Fira Sans',
    color: 'black',
    fontWeight: 'bold',
    fontSize: 33,
    paddingLeft: 20,
    paddingTop: 15,
    //textAlign: 'left',
    //paddingTop: 10,
    //paddingLeft: 20,
  },
  scoreDescription: {
    fontFamily: 'Fira Sans',
    color: 'black',
    fontStyle: 'italic',
    fontSize: 18,
    textAlign: 'left',
    width: 300,
    paddingLeft: 20,
    paddingTop: 3,
  },
  firstgradeDate: {
    fontFamily: 'Fira Sans',
    color: 'black',
    //fontStyle: 'italic',
    fontWeight: 'bold',
    fontSize: 33,
    textAlign: 'left',
    width: 500,
    paddingLeft: 20,
    paddingTop: 72,
  },
  gradeDates: {
    fontFamily: 'Fira Sans',
    color: 'black',
    //fontStyle: 'italic',
    fontWeight: 'bold',
    fontSize: 33,
    textAlign: 'left',
    width: 500,
    paddingLeft: 20,
    paddingTop: 40,
  },
  quizBackground: {
    resizeMode: 'contain',
    width: Dimensions.get('window').width - 10,
    height: Dimensions.get('window').height,
    position: 'absolute',
    top: 320,
    bottom: 0,
    left: 5,
    right: 5,
  },
  beginQuizText: {
    fontFamily: 'Fira Sans',
    color: 'white',
    //fontStyle: 'italic',
    fontWeight: 'bold',
    fontSize: 35,
    textAlign: 'left',
    width: 500,
    paddingLeft: 20,
    paddingTop: 40,
    position: 'absolute',
    top: 305,
    bottom: 0,
    left: 5,
    right: 5,
  },
  letsGoToQuiz: {
    resizeMode: 'contain',
    //paddingLeft: 20,
    paddingTop: 40,
    paddingRight: 20,
    //position: 'center',
    top: 75,
    bottom: 0,
    left: 80,
    right: 20,
  }
});